Libpitt/68 generalize
hubmapconsortium/data-ingest-board pull request #69
Opened 2023-08-23 20:22 UTC by libpitt

Change log:
https://github.com/hubmapconsortium/data-ingest-board/issues/62
https://github.com/hubmapconsortium/data-ingest-board/issues/63
https://github.com/hubmapconsortium/data-ingest-board/issues/64
https://github.com/hubmapconsortium/data-ingest-board/issues/67
https://github.com/hubmapconsortium/data-ingest-board/issues/68

There's a lot of changes. Can you @DerekFurstPitt @yuanzhou @maxsibilla help me test for bugs. 

I will set up HuBMAP's ingest-api in the meantime.

2023-08-23 21:40 UTC, DerekFurstPitt approved these changes

2023-08-25 19:34 UTC, yuanzhou requested changes
@libpitt it looks great and I did some local testing too. In addition to the commented tweaks, can you also make one more change?

We really don't need the part after the seconds in the last modified column. I had pointed this out to @DerekFurstPitt and he mentioned something about sorting. You two may talk about the details. It takes more horizontal space and that decimal second doesn't really convery much meaning to the end users.

![image](https://github.com/hubmapconsortium/data-ingest-board/assets/195873/093f1ab5-8165-4c51-b6e5-2fa1e0b598a0)

2023-08-25 19:34 UTC, yuanzhou commented on src/example.env
> +NEXT_PUBLIC_UPLOAD_URL = https://ingest-api.dev.hubmapconsortium.org/uploads/data-status
I had noticed this earlier when @DerekFurstPitt created the data-ingest-board. @libpitt It's a good opportunity now that we expand the config variable for reuse purpose as below:

```
NEXT_PUBLIC_API_BASE = https://ingest-api.dev.hubmapconsortium.org
NEXT_PUBLIC_DATASET_URL = $NEXT_PUBLIC_API_BASE/datasets/data-status
NEXT_PUBLIC_UPLOAD_URL = $NEXT_PUBLIC_API_BASE/uploads/data-status
```

2023-08-25 19:34 UTC, yuanzhou commented on src/package.json
>    "version": "1.1.0",
@libpitt can you update the version to 1.2.0 in both `package.json` and the VERSION file?

2023-08-25 20:48 UTC, yuanzhou approved these changes
@libpitt thanks for the tweaks! @maxsibilla once you also finish the review and approve, I'll get it merged and deployed on DEV along with the ingest-api PR: https://github.com/hubmapconsortium/ingest-api/pull/361

2023-08-28 15:31 UTC, maxsibilla commented
I updated the README and added example.sennet.env file. @libpitt I think you should add some additional columns to be searchable such as:
- status
- organ type
- provider experiment ID

Also I am not sure the best way to handle this but the tooltip in this scenario should display the header name:
<img width="284" alt="image" src="https://github.com/hubmapconsortium/data-ingest-board/assets/7218802/3b10eba1-d542-441a-9b55-f98a0c4daa47">

2023-08-29 15:13 UTC, merged