Libpitt/88 user instructions
hubmapconsortium/data-ingest-board pull request #90
Opened 2023-10-12 16:24 UTC by libpitt

**Change log:**
1. Add user email to header #89 
   - Refactor header code to use react bootstrap `Nav` component so as to get mobile view ui
   - Move nav related code to own component `AppNavBar`
2. Add user unauthorized message #88 
   - Add accommodating styles
   - Add `/login` link (pages/login.js)
   - Make use of `response.data` in `verifyInReadGroup` to specifically check read privs on each token check
   
### IMPORTANT:
SenNet, update to: `NEXT_PUBLIC_PRIVS_GROUP_URL = $NEXT_PUBLIC_API_BASE/privs`
HuBMAP, add: `NEXT_PUBLIC_PRIVS_GROUP_NAME = HuBMAP Read`

2023-10-12 16:32 UTC, maxsibilla approved these changes
@libpitt Message looks good for SenNet at least
<img width="1407" alt="image" src="https://github.com/hubmapconsortium/data-ingest-board/assets/7218802/f60efba1-f6d2-4e42-8ac5-d9217f37d29d">

2023-10-12 16:35 UTC, maxsibilla commented
@yuanzhou I am tagging you as a reviewer as well on this. The main ask for this PR is 

1. Add the user's email to the navbar for clarity, consistency across the UIs, and to help us with troubleshooting account access problems
2. Add a check for the use case that a user has globus access but is not a member of the default read group (or has read access). In this case we want to show a message explaining what the user needs to do with links to the member registration page and the help desk.

2023-10-17 15:00 UTC, yuanzhou requested changes

2023-10-17 15:06 UTC, libpitt commented on src/components/AppLogin/index.js
> +                <p>Once you have confirmed your registration information you can <a href='/login' className='lnk--ic'>log in <LoginOutlined /></a> again.</p>
@yuanzhou It shouldn't, there is a login page. Unless misunderstanding what you're referring to...
![:login-page](https://github.com/hubmapconsortium/data-ingest-board/assets/115558393/2c1cd0cb-7600-4b12-8dca-fe07c4fdea53)

2023-10-17 15:09 UTC, yuanzhou commented on src/components/AppLogin/index.js
> +                <p>Once you have confirmed your registration information you can <a href='/login' className='lnk--ic'>log in <LoginOutlined /></a> again.</p>
I didn't check locally, on the current released version, I got 404 for both HuBMAP and SenNet
<img width="571" alt="Screenshot 2023-10-17 at 11 08 29 AM" src="https://github.com/hubmapconsortium/data-ingest-board/assets/195873/270397d8-2149-4248-9b1b-cb4ed4be5fa7">

2023-10-17 15:32 UTC, yuanzhou approved these changes

2023-10-17 15:33 UTC, merged